---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-client
  labels:
    death-star-project: online-boutique
    app: ubuntu-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-client
  template:
    metadata:
      labels: 
        app: ubuntu-client
      name: ubuntu-client
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: hr-client
        image: ubuntu
        resources:
          requests:
            cpu: 2
            memory: 2Gi
        command:  ["/bin/sh", "-c"]
        args:
          - apt-get -y update &&
            apt-get -y upgrade &&
            apt-get -y install dnsutils git vim python3 python3-aiohttp libssl-dev libz-dev luarocks iputils-ping lynx build-essential gcc bash curl &&
            luarocks install luasocket &&
            git clone https://github.com/giltene/wrk2.git &&
            cd wrk2 &&
            make &&
            cd .. &&
            git clone https://github.com/wg/wrk.git &&
            cd wrk &&
            make &&
            sleep 365d
        imagePullPolicy: Always
        # restartPolicy: Always
      imagePullSecrets:
        - name: regcred